### ISSUE TITLE
Create css file for webpage

### ISSUE THREAD

**Issue by kenny101** [kenny101/sp21-cse110-lab3#1]
create css file for webpage and add styling such as background color, text alignment, and fonts

**Comment by DineshKoushik** [comment]
@kenny101 , can you assign this to me?

**Comment by DineshKoushik** [comment]
Hi @kenny101 , can you review the PR please.

**Comment by kenny101** [comment]
@DineshKoushik Hey thanks so much for taking a look at my 💩code. But this is an assignment for a class at my university so I cannot merge this code onto my repo. Thanks again! I really didn't expect anyone to find this repo but I truly appreciate the help. 😂
